name: "my-upload-artifact"
description: "my proxy of calling actions/upload-artifact"
inputs:
  name:
    description: "artifact name"
    required: true
  path:
    description: "artifact path"
    required: true
  if-no-files-found:
    description: "if no files found, do not fail the job, [warn]/error/ignore"
    required: false
    default: "warn"

runs:
  using: "composite"
  steps:
    - name: upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        if-no-files-found: ${{ inputs.if-no-files-found }}
