name: "record begin time on windows"
description: "record begin time on windows"
outputs:
  now:
    description: "begin time"
    value: ${{steps.record.outputs.now}}
runs:
  using: "composite"
  steps:
    - id: record
      run: |
        $now = [TimeZoneInfo]::ConvertTimeFromUtc([DateTime]::UtcNow, [TimeZoneInfo]::FindSystemTimeZoneById("China Standard Time")).ToString("HH:mm:ss@yyyy-MM-dd", $null)
        echo "now=${now}" >> $Env:GITHUB_OUTPUT
      shell: powershell
