name: "send weixin api message"
description: "send weixin api message"
inputs:
  weixin:
    description: "credential to call weixin API"
    required: true
  result:
    description: "main job result message"
    required: true
  now:
    description: "action begin time"
    required: true
  href:
    description: "filename url for web access"
    required: false

runs:
  using: "composite"
  steps:
    - name: send weixin in bash
      # if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: |
        repo=${{github.event.repository.name}}
        ref=${GITHUB_REF##*/}
        result=${{inputs.result}}
        now=${{inputs.now}}
        href="${{inputs.href}}"
        message=$(cat <<-END
        ${repo}/${ref}
        ${result}_${now}${href}
        END
        )
        echo "message=${message}"
        
        encrypted="U2FsdGVkX19xlWjV/OyDgsWs7SDdWQgw1Ghspe/65jTJxnzGgSv8/ECLajCWm9G3
        tSCdY9Yctx7YNekbz+R1eGd7G90nKrVpJFhemSZw3o4lyKSDgqtyptFKPEM75eqJ
        mSRIc8N51Wt+C/YEP84GvA=="
        decrypted=$(echo ${encrypted} | openssl aes-256-cbc -pbkdf2 -d -a -pass pass:${{inputs.weixin}})
        token=$(echo $(curl -sS "https://qyapi.weixin.qq.com/cgi-bin/gettoken?${decrypted}") | jq --raw-output .access_token)
          
        header="Content-Type: application/json"
        url="https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=${token}"
        body='{
          "touser": "'"${{github.actor}}"'",
          "msgtype": "text",
          "agentid": "1000002",
          "text": {
            "content": "\u4F60\u597D"
          }
        }'
        echo "body=${body}"
        curl -X POST -H "${header}" -d "${body}" "${url}"
    
    # - name: send weixin in windows
    #   if: runner.os == 'Windows'
    #   shell: bash
    #   run: |
    #     repo=${{github.event.repository.name}}
    #     ref=${GITHUB_REF##*/}
    #     result=${{inputs.result}}
    #     now=${{inputs.now}}
    #     href="${{inputs.href}}"
    #     message=$(cat <<-END
    #     ${repo}/${ref}
    #     ${result}_${now}${href}
    #     END
    #     )
        
    #     encrypted="U2FsdGVkX19xlWjV/OyDgsWs7SDdWQgw1Ghspe/65jTJxnzGgSv8/ECLajCWm9G3
    #     tSCdY9Yctx7YNekbz+R1eGd7G90nKrVpJFhemSZw3o4lyKSDgqtyptFKPEM75eqJ
    #     mSRIc8N51Wt+C/YEP84GvA=="
    #     decrypted=$(echo ${encrypted} | openssl aes-256-cbc -pbkdf2 -d -a -pass pass:${{inputs.weixin}})
    #     token=$(echo $(curl -sS "https://qyapi.weixin.qq.com/cgi-bin/gettoken?${decrypted}") | jq --raw-output .access_token)
          
    #     header="Content-Type: application/json"
    #     url="https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=${token}"
    #     curl -X POST -H ${header} -d ${body} ${url}
