name: "send weixin api message"
description: "send weixin api message"
inputs:
  weixin:
    description: "credential to call weixin API"
    required: true
  result:
    description: "main job result message"
    required: true
  now:
    description: "action begin time"
    required: true
  href:
    description: "filename url for web access"
    required: false

runs:
  using: "composite"
  steps:
    - name: call API to send weixin
      run: |
        repo=${{github.event.repository.name}}
        ref=${GITHUB_REF##*/}
        result=${{inputs.result}}
        now=${{inputs.now}}
        href="${{inputs.href}}"
        message=$(printf "${repo}/${ref}\n${result}_${now}${href}")
        newmessage=$(cat << EOF
        ${repo}/${ref}
        ${result}_${now}${href}
        EOF)
        newmessage1=$(cat <<-END
        ${repo}/${ref}
        ${result}_${now}${href}
        END
        )
        echo $message
        echo $newmessage
        echo $newmessage1
        curl -G "https://f.w9.work/api/SendWeiXinMessage?code=${{inputs.weixin}}" --data-urlencode "text=${newmessage1}"

      shell: bash
