name: "record begin time"
description: "record begin time"
outputs:
  now:
    description: "begin time"
    value: ${{steps.record.outputs.now}}
runs:
  using: "composite"
  steps:
    - id: record
      run: |
        export now="$(TZ=Asia/Shanghai date +%H:%M:%S@%Y-%m-%d)"
        echo "::set-output name=now::${now}"
      shell: bash
