name: "my-setup-dotnet"
description: "my proxy of calling actions/setup-dotnet"
inputs:
  dotnet-version:
    description: "dotnet version"
    required: true

runs:
  using: "composite"
  steps:
    - name: setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
